# Generated by Django 4.0.5 on 2022-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='years_of_experience',
            field=models.IntegerField(),
        ),
    ]
